language: android
jdk: oraclejdk8
env:
  global:
    - ANDROID_TARGET=android-27
    - ANDROID_ABI=armeabi-v7a
android:
  components:
  - tools
  - platform-tools
  - build-tools-27.0.3
  - android-27
  - extra-android-m2repository
  - sys-img-${ANDROID_ABI}-${ANDROID_TARGET}
before_install:
  - chmod +x gradlew
  - yes | sdkmanager "platforms;android-27"
script:
  - ./gradlew assemble
  - ./gradlew build testDebugUnitTest
after_success:
  - if [ -e ./gradlew ]; then ./gradlew jacocoTestReportDebug;else gradle jacocoTestReport;fi
  - bash <(curl -s https://codecov.io/bash)
